# SwiftLint Configuration for GabGab
# Based on Swift best practices and project conventions

# Disabled rules (too strict for this project)
disabled_rules:
  - cyclomatic_complexity  # Allow complex logic when needed
  - file_length            # Files are already well-structured
  - function_body_length  # Some functions need to be longer
  - identifier_name        # Allow descriptive names
  - line_length            # Allow longer lines for readability
  - type_name              # Allow descriptive type names
  - trailing_whitespace   # Handled by SwiftFormat

# Included paths
included:
  - Sources
  - Tests

# Excluded paths
excluded:
  - .build
  - .swiftpm
  - Package.resolved

# Reporter
reporter: "xcode"

# Rule configurations
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rule configurations
force_unwrapping:
  severity: warning  # Warn instead of error for force unwraps

force_cast:
  severity: warning

function_body_length:
  warning: 100
  error: 200

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3
